### ISSUE TITLE
Model refactor

### ISSUE THREAD

**Issue by amZotti** [team-oath/uncovery#78]
Models need to refactored in the following ways:

1) The models should be modularized into their own files based what they do:
     -create
     -retrieve
     -update
     -delete

2) Models should be renamed to 'services' or something else that better represents them. The term 'model' implies an object representing a piece of datum. Currently, everything in our models are functions so they should be renamed for readability and technical accuracy.

**Comment by mrblueblue** [comment]
I think this has been achieved

**Comment by mrblueblue** [comment]
done
